version: '3.4'

services:
  web:
    build: ./app
    command: gunicorn ba_django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    ports:
      - 8000:8000
